[package]
name = "advent_of_code_2021"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2021"

[dependencies]
hashbrown = "0.11.2"
itertools = "0.10.1"

[dependencies.commons]
path = "../commons"
