[package]
name = "advent_of_code_2021"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2021"

[dependencies]
hashbrown = "0.12.1"
itertools = "0.10.3"

[dependencies.commons]
path = "../commons"
