[package]
name = "advent_of_code_2019"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2021"

[dependencies]
hashbrown = "0.12.3"
itertools = "0.10.5"

[dependencies.commons]
path = "../commons"
