[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2018"

[profile.release]
lto = 'thin'

[dependencies]
anyhow = "1.0.34"
bitflags = "1.2.1"
itertools = "0.9.0"
structopt = "0.3.20"
thiserror = "1.0.22"
