[package]
name = "commons"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2018"

[dependencies]
itertools = "0.10.1"
color-eyre = "0.5.11"

[dependencies.clap]
version = "2.33.3"
default-features = false
features = [ "suggestions" ]
