[package]
name = "commons"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2021"

[dependencies]
itertools = "0.10.3"
eyre = "0.6.8"
num= "0.4.0"

[dependencies.clap]
version = "3.1.18"
default-features = false
features = [ "suggestions", "std", "cargo" ]
