[package]
name = "commons"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2021"

[dependencies]
itertools = "0.10.3"
eyre = "0.6.5"
num= "0.4.0"

[dependencies.clap]
version = "2.34.0"
default-features = false
features = [ "suggestions" ]
