[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["Remy Duval <remy_duval@laposte.net>"]
edition = "2021"

[dependencies]
hashbrown = "0.13.2"
itertools = "0.10.5"

[dependencies.commons]
path = "../commons"
